A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('panel/', include('panel.urls')),
    path('movie/', include('movie.urls')),
    path('finance/', include('finance.urls')),
    path('api/', include('api.urls')),
]

finance/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views


app_name = 'finance'
urlpatterns = [
    path('plan/', TemplateView.as_view(template_name='finance/plan.html'), name='plan'),
    path('plan/pay/', views.PlanPayView.as_view(), name='pay_plan'),
    path('plan/verify/', views.PlanPayVerify.as_view(), name='pay_verify'),
]

movie/urls.py
from django.urls import path

from . import views


app_name = 'movie'

urlpatterns = [
    path('detail/<slug:slug>/', views.MovieDetailView.as_view(), name='detail'),
    path('part_detail/<int:pk>/<slug:slug>/', views.PartDetailSeasonView.as_view(), name='part_detail'),
    path('favorite/<int:pk>/', views.MovieFavoriteAction.as_view(), name='favorite'),
    path('catalogue/', views.MovieCatalogueView.as_view(), name='catalogue'),
    path('category/', views.MovieCategoryView.as_view(), name='category'),
]

movie/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.db.models import Avg, Sum, Count

from .choices import TYPE_CHOICES, QUALITY_CHOICES, COUNTRY_CHOICES, IRAN
from .managers import IsActiveManager, MovieManager, MovieCommentManager


class BaseMovieModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Genre(models.Model):
    name = models.CharField(max_length=32, verbose_name=_('name'))
    english_name = models.CharField(max_length=32, verbose_name=_('english name'))
    slug = models.SlugField(max_length=40, verbose_name=_('slug'))
    image_cover = models.ImageField(verbose_name=_('image'))

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/movie/category/?genre={self.slug}'


class Movie(BaseMovieModel):
    name = models.CharField(max_length=120, verbose_name=_('name'))
    english_name = models.CharField(max_length=120, verbose_name=_('english name'))
    slug = models.SlugField(max_length=120, verbose_name=_('slug'), db_index=True)
    description = models.TextField(verbose_name=_('description'))
    poster = models.ImageField(verbose_name='poster', null=True, blank=True)
    image_cover = models.ImageField(verbose_name=_('image cover'))
    image_background = models.ImageField(verbose_name=_('image background'))
    publish_at = models.DateField(verbose_name=_('publish_at'))
    created_at = models.DateField(verbose_name=_('created at'))
    trailer = models.CharField(max_length=240, verbose_name=_('trailer'), null=True, blank=True)
    type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES, default=1, verbose_name=_('type'))
    quality = models.PositiveSmallIntegerField(choices=QUALITY_CHOICES, default=1, verbose_name=_('quality'))
    time_in_minutes = models.PositiveIntegerField(verbose_name=_('time in minutes'))
    ages = models.PositiveSmallIntegerField(verbose_name=_('ages'))
    is_free = models.BooleanField(default=True, verbose_name=_('is free'))
    country = models.CharField(max_length=34, choices=COUNTRY_CHOICES, verbose_name=_('country'))
    is_active = models.BooleanField(default=True)

    default_manager = models.Manager()
    objects = MovieManager()

    class Meta:
        verbose_name = _('Movie')
        verbose_name_plural = _('Movies')
        ordering = ('-publish_at',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('movie:detail', args=[self.slug])

    def get_comments(self):
        return self.comments.filter(is_active=True)

    def get_comment_count(self):
        return self.comments.filter(is_active=True).count()

    def get_reviews(self):
        return self.reviews.filter(is_active=True)

    def get_review_count(self):
        return self.reviews.filter(is_active=True).count()

    def get_avg_rate(self):
        rate = self.reviews.all().aggregate(avg_rate=Avg('rate'))
        if rate['avg_rate']:
            return round(rate['avg_rate'], 1)
        return 8

    @classmethod
    def get_favorites(cls):
        return cls.objects.all().annotate(favorite_count=Count('favorites')).order_by('-favorite_count')[:12]

    @classmethod
    def get_all_favorites(cls):
        return cls.objects.all().annotate(favorite_count=Count('favorites')).order_by('-favorite_count')

    @classmethod
    def get_news(cls):
        return cls.objects.all()[:12]

    @classmethod
    def get_best_rates(cls):
        return cls.default_manager.all().annotate(avg_rate=Sum('reviews__rate')).order_by('-avg_rate')

    @classmethod
    def get_recommend_movie(cls, user):
        genres = user.get_favorite_genres()
        return cls.objects.filter(genres__genre__id__in=genres).distinct()[:5]

    def get_genres(self):
        return self.genres.all()

    def get_similar_movies(self):
        return Movie.objects.filter(genres__genre_id__in=self.genres.all().values('genre__id')).distinct()[:12]


class MovieGenre(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='genres', verbose_name=_('movie'))
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='movies', verbose_name=_('genre'))

    def __str__(self):
        return f'{self.movie}-{self.genre}'


class FilmMovie(Movie):

    class Meta:
        proxy = True


class SeriesMovie(Movie):
    class Meta:
        proxy = True


class FilmLink(BaseMovieModel):
    film = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='links')
    name = models.CharField(max_length=120)
    quality = models.IntegerField(verbose_name=_('quality'))
    volume = models.CharField(max_length=32)
    link = models.CharField(max_length=240)

    class Meta:
        verbose_name = _('Film Link')
        verbose_name_plural = _('Film Links')
        ordering = ('-quality',)

    def __str__(self):
        return f'{self.film.name[:32]}---{self.name}'


class FilmSubtitle(models.Model):
    film = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='subtitles', verbose_name=_('film'))
    language = models.CharField(max_length=32, choices=COUNTRY_CHOICES, default=IRAN, verbose_name=_('language'))
    subtitle = models.FileField(max_length=240, verbose_name=_('subtitle'))

    def __str__(self):
        return f'{self.film}-{self.language}'


class SeriesSeason(BaseMovieModel):
    series = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='seasons', verbose_name=_('series'))
    season = models.PositiveSmallIntegerField(verbose_name=_('season'))
    name = models.CharField(max_length=120)
    image_background = models.ImageField(verbose_name=_('image background'))

    class Meta:
        verbose_name = _('Series Season')
        verbose_name_plural = _('Series Seasons')
        ordering = ('season',)

    def __str__(self):
        return f'series name: {self.series.name[:32]} -- season: {self.season}'


class SeasonPart(BaseMovieModel):
    season = models.ForeignKey(SeriesSeason, on_delete=models.CASCADE, related_name='parts',
                               verbose_name=_('Season Part'))
    name = models.CharField(max_length=64, verbose_name=_('name'))
    poster = models.ImageField(verbose_name=_('poster'))
    # TODO: below is true and up is false
    # image_cover = models.ImageField(verbose_name=_('image cover'))
    part = models.PositiveSmallIntegerField(verbose_name=_('part'))

    class Meta:
        verbose_name = _('Season Part')
        verbose_name_plural = _('Season Parts')
        ordering = ('part',)

    def __str__(self):
        return f'{self.season} -- part: {self.part}'

    def get_absolute_url(self):
        return reverse('movie:part_detail', args=[self.pk, self.season.series.slug])


class SeasonPartSubtitle(models.Model):
    season_part = models.ForeignKey(SeasonPart,
                                    on_delete=models.CASCADE, related_name='subtitles', verbose_name=_('season part'))
    language = models.CharField(max_length=32, choices=COUNTRY_CHOICES, default=IRAN, verbose_name=_('language'))
    subtitle = models.FileField(max_length=240, verbose_name=_('subtitle'))

    def __str__(self):
        return f'{self.season_part}-{self.language}'


class PartLink(BaseMovieModel):
    season_part = models.ForeignKey(SeasonPart, on_delete=models.CASCADE, related_name='links',
                                    verbose_name=_('part link'))
    name = models.CharField(max_length=64, verbose_name=_('name'))
    quality = models.IntegerField(verbose_name=_('quality'))
    volume = models.CharField(max_length=34)
    link = models.CharField(max_length=240)

    class Meta:
        verbose_name = _('Part Link')
        verbose_name_plural = _('Part Links')
        ordering = ('-quality',)

    def __str__(self):
        return f'{self.season_part} -- quality: {self.quality}'


class MovieComment(BaseMovieModel):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comments',
                             verbose_name=_('user'))
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='comments', verbose_name=_('movie'))
    body = models.TextField(verbose_name=_('body'))
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children',
                               verbose_name=_('parent'), null=True, blank=True)
    is_reply = models.BooleanField(default=False, verbose_name=_('is reply'))
    is_read = models.BooleanField(default=False, verbose_name=_('is read'))
    is_active = models.BooleanField(default=False, verbose_name=_('is active'))

    default_manager = models.Manager()
    objects = MovieCommentManager()

    class Meta:
        verbose_name = _('Movie Comment')
        verbose_name_plural = _('Movie Comments')
        ordering = ('-created',)

    def __str__(self):
        return f'{self.user} - {self.movie}'


class MovieReview(BaseMovieModel):
    RATE_CHOICES = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10),
    )
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='reviews',
                             verbose_name=_('user'))
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews', verbose_name=_('movie'))
    rate = models.PositiveSmallIntegerField(choices=RATE_CHOICES, verbose_name=_('rate'))
    subject = models.CharField(max_length=120, verbose_name=_('subject'))
    description = models.TextField(verbose_name=_('body'))
    is_read = models.BooleanField(default=False, verbose_name=_('is read'))
    is_active = models.BooleanField(default=False, verbose_name=_('is active'))

movie/forms.py
from django import forms

from .models import MovieComment, MovieReview


error_msg = {
    "invalid": 'مقدار وارد شده معتبر نمی باشد',
    "required": 'این فیلد نمی تواند خالی باشد'
}


class CommentMovieForm(forms.ModelForm):
    class Meta:
        model = MovieComment
        fields = ('body',)
        widgets = {
            "body": forms.Textarea(attrs={"class": 'sign__textarea', "placeholder": 'چیزی بنویسید...'})
        }
        error_messages = {"body": error_msg}


class ReviewMovieForm(forms.ModelForm):
    class Meta:
        model = MovieReview
        fields = ('subject', 'rate', 'description')

        error_messages = {
            "subject": error_msg,
            "rate": error_msg,
            "description": error_msg
        }

movie/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import View, DetailView, FormView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Movie, MovieComment, MovieReview, SeasonPart, Genre, MovieView
from core.forms import MagazineForm
from .forms import CommentMovieForm, ReviewMovieForm
from .actions import category_action


class MovieDetailView(DetailView, FormView):
    model = Movie
    template_name = 'movie/detail.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    queryset = Movie.objects.all()

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            view = MovieView.objects.filter(user=request.user, movie=self.get_object())
            movie = self.get_object()
            if not view and movie:
                MovieView.objects.create(user=request.user, movie=self.get_object())
        return super().dispatch(request, *args, **kwargs)

    def get_form_class(self):
        form_class = self.request.POST.get('form_class')
        if self.request.user.is_authenticated:
            if form_class == 'comment':
                return CommentMovieForm
            elif form_class == 'review':
                return ReviewMovieForm
        return MagazineForm

    def get_success_url(self):
        return self.request.path

    def form_invalid(self, form):
        return render(self.request, self.template_name, {"object": self.get_object(), "form": form})

    def form_valid(self, form):
        form_class = self.get_form_class()
        if form_class == CommentMovieForm:
            MovieComment.objects.create(user=self.request.user, movie=self.get_object(), body=form.cleaned_data['body'])
        elif form_class == ReviewMovieForm:
            cd = form.cleaned_data
            MovieReview.objects.create(user=self.request.user, movie=self.get_object(),
                                       rate=cd['rate'], subject=cd['subject'], description=cd['description'])
        else:
            form.save()
        return super().form_valid(form)


class PartDetailSeasonView(MovieDetailView):
    template_name = 'movie/part_detail.html'

    def get_context_data(self, **kwargs):
        part = get_object_or_404(SeasonPart, pk=self.kwargs['pk'])
        obj = get_object_or_404(Movie, slug=self.kwargs['slug'])
        return {
            "part": part,
            "object": obj
        }

    def get_object(self, queryset=None):
        return get_object_or_404(Movie, slug=self.kwargs['slug'])

    def form_invalid(self, form):
        context = self.get_context_data()
        return render(self.request, self.template_name,
                      {"form": form,
                       "part": context['part'],
                       "object": context['object']}
                      )


class MovieFavoriteAction(LoginRequiredMixin, View):
    def get(self, request, pk):
        movie = get_object_or_404(Movie, pk=pk)
        favorite = request.user.favorites.filter(movie=movie)
        if favorite.exists():
            favorite.delete()
        else:
            request.user.favorites.create(movie=movie)
        url = reverse_lazy('movie:detail', args=[movie.slug])
        return redirect(request.GET.get('next', url))


class MovieCatalogueView(ListView):
    model = Genre
    template_name = 'movie/catalogue.html'
    queryset = Genre.objects.all()


class MovieCategoryView(ListView):
    model = Movie
    template_name = 'movie/category.html'
    paginate_by = 20

    def get_queryset(self):
        genre_slug = self.request.GET.get('genre')
        action = self.request.GET.get('action')
        action_info = category_action(action=action, genre=genre_slug)
        self.category = action_info['category']
        return action_info['queryset']

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, object_list=object_list, **kwargs)
        context['category'] = self.category
        return context

movie/templates/movie/shared/not_free.html
<div class="col-12 col-xl-8">
    <!-- trailer -->
    {% include 'movie/shared/trailer.html' %}
    <!-- end trailer -->

    <!-- article content -->
    <div class="article__content">
        <div class="article__btns">
            <a href="{% url 'finance:plan' %}" class="article__btn">خرید اشتراک جنگو مووی</a>
        </div>
    </div>
    <!-- end article content -->
</div>

    <!-- share -->
    {% include 'movie/shared/share.html' %}
    <!-- end share -->

movie/templates/movie/shared/series_part.html
{% load static %}

<div class="col-12 col-xl-8">
    <!-- trailer -->
    {% if object.trailer %}
    <a href="{{ object.trailer }}"
       class="article__trailer open-video">
        <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd"
                  d="M11 1C16.5228 1 21 5.47716 21 11C21 16.5228 16.5228 21 11 21C5.47716 21 1 16.5228 1 11C1 5.47716 5.47716 1 11 1Z"
                  stroke-linecap="round" stroke-linejoin="round"></path>
            <path fill-rule="evenodd" clip-rule="evenodd"
                  d="M14.0501 11.4669C13.3211 12.2529 11.3371 13.5829 10.3221 14.0099C10.1601 14.0779 9.74711 14.2219 9.65811 14.2239C9.46911 14.2299 9.28711 14.1239 9.19911 13.9539C9.16511 13.8879 9.06511 13.4569 9.03311 13.2649C8.93811 12.6809 8.88911 11.7739 8.89011 10.8619C8.88911 9.90489 8.94211 8.95489 9.04811 8.37689C9.07611 8.22089 9.15811 7.86189 9.18211 7.80389C9.22711 7.69589 9.30911 7.61089 9.40811 7.55789C9.48411 7.51689 9.57111 7.49489 9.65811 7.49789C9.74711 7.49989 10.1091 7.62689 10.2331 7.67589C11.2111 8.05589 13.2801 9.43389 14.0401 10.2439C14.1081 10.3169 14.2951 10.5129 14.3261 10.5529C14.3971 10.6429 14.4321 10.7519 14.4321 10.8619C14.4321 10.9639 14.4011 11.0679 14.3371 11.1549C14.3041 11.1999 14.1131 11.3999 14.0501 11.4669Z"
                  stroke-linecap="round" stroke-linejoin="round"></path>
        </svg>
        نمایش تیزر
    </a>
    {% endif %}
    <!-- end trailer -->

    <!-- article content -->
    <div class="article__content">
        <h1>{{ part.name }} فصل {{ part.season.season }}</h1>

        <ul class="list">
            <li>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="M22,9.67A1,1,0,0,0,21.14,9l-5.69-.83L12.9,3a1,1,0,0,0-1.8,0L8.55,8.16,2.86,9a1,1,0,0,0-.81.68,1,1,0,0,0,.25,1l4.13,4-1,5.68A1,1,0,0,0,6.9,21.44L12,18.77l5.1,2.67a.93.93,0,0,0,.46.12,1,1,0,0,0,.59-.19,1,1,0,0,0,.4-1l-1-5.68,4.13-4A1,1,0,0,0,22,9.67Zm-6.15,4a1,1,0,0,0-.29.88l.72,4.2-3.76-2a1.06,1.06,0,0,0-.94,0l-3.76,2,.72-4.2a1,1,0,0,0-.29-.88l-3-3,4.21-.61a1,1,0,0,0,.76-.55L12,5.7l1.88,3.82a1,1,0,0,0,.76.55l4.21.61Z"/>
                </svg>
                9.7
            </li>
            <li>{{ object.genres.first.get_genre_display }}</li>
            <li>{{ object.publish_at }}</li>
            <li>{{ object.time_in_minutes }} دقیقه</li>
            <li>{{ object.ages }}+</li>
        </ul>

        <p>{{ object.description }}</p>
    </div>
    <!-- end article content -->
</div>

<!-- video player -->
<div class="col-12 col-xl-8">
    <video controls crossorigin playsinline
           poster="{{ object.poster.url }}" id="player">
        <!-- Video files -->
        {% for movie_link in part.links.all %}
        <source src="{{ movie_link.link }}" type="video/mp4"
                size="{{ movie_link.quality }}">
        {% endfor %}
        <!-- Caption files -->
        {% for sub in part.subtitles.all %}
        <track kind="captions" label="{{ sub.get_language_display }}" srclang="{{ sub.language }}"
               src="{{ sub.subtitle.url }}">
        {% endfor %}
        <a href="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4" download>دانلود</a>
    </video>

    <div class="article__actions article__actions--details">
        <div class="article__download">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M21,14a1,1,0,0,0-1,1v4a1,1,0,0,1-1,1H5a1,1,0,0,1-1-1V15a1,1,0,0,0-2,0v4a3,3,0,0,0,3,3H19a3,3,0,0,0,3-3V15A1,1,0,0,0,21,14Zm-9.71,1.71a1,1,0,0,0,.33.21.94.94,0,0,0,.76,0,1,1,0,0,0,.33-.21l4-4a1,1,0,0,0-1.42-1.42L13,12.59V3a1,1,0,0,0-2,0v9.59l-2.29-2.3a1,1,0,1,0-1.42,1.42Z"/>
            </svg>
            دانلود :
            {% for movie_link in part.links.all %}
            <a href="{{ movie_link.link }}" download="#">{{ movie_link.name }}</a>
            {% endfor %}
        </div>

        <!-- add .active class -->
        {% if request.user.is_authenticated %}
        <a class="article__favorites" href="{% url 'movie:favorite' object.pk %}" type="button">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M16,2H8A3,3,0,0,0,5,5V21a1,1,0,0,0,.5.87,1,1,0,0,0,1,0L12,18.69l5.5,3.18A1,1,0,0,0,18,22a1,1,0,0,0,.5-.13A1,1,0,0,0,19,21V5A3,3,0,0,0,16,2Zm1,17.27-4.5-2.6a1,1,0,0,0-1,0L7,19.27V5A1,1,0,0,1,8,4h8a1,1,0,0,1,1,1Z"></path>
            </svg>
            افزودن به علاقه مندی
        </a>
        {% endif %}
    </div>
</div>
<!-- end video player -->

<!-- series -->
<div dir="ltr" class="col-12">
    {% for season in object.seasons.all %}
    <div class="series-wrap">
        <h3 class="series-wrap__title">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M9,10a1,1,0,0,0-1,1v2a1,1,0,0,0,2,0V11A1,1,0,0,0,9,10Zm12,1a1,1,0,0,0,1-1V6a1,1,0,0,0-1-1H3A1,1,0,0,0,2,6v4a1,1,0,0,0,1,1,1,1,0,0,1,0,2,1,1,0,0,0-1,1v4a1,1,0,0,0,1,1H21a1,1,0,0,0,1-1V14a1,1,0,0,0-1-1,1,1,0,0,1,0-2ZM20,9.18a3,3,0,0,0,0,5.64V17H10a1,1,0,0,0-2,0H4V14.82A3,3,0,0,0,4,9.18V7H8a1,1,0,0,0,2,0H20Z"/>
            </svg>
            فصل {{ season.season }}
        </h3>
        <div class="section__carousel-wrap">
            <div class="section__series owl-carousel" id="series">
                {% for part in season.parts.all %}
                <div class="series">
                    <a href="{{ part.get_absolute_url }}" class="series__cover">
                        <img src="{{ part.poster.url }}" alt="">
                        <span>
                            <svg width="22" height="22" viewBox="0 0 22 22" fill="none"
                                 xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd"
                                                                          clip-rule="evenodd"
                                                                          d="M11 1C16.5228 1 21 5.47716 21 11C21 16.5228 16.5228 21 11 21C5.47716 21 1 16.5228 1 11C1 5.47716 5.47716 1 11 1Z"
                                                                          stroke-linecap="round"
                                                                          stroke-linejoin="round"/><path
                                    fill-rule="evenodd" clip-rule="evenodd"
                                    d="M14.0501 11.4669C13.3211 12.2529 11.3371 13.5829 10.3221 14.0099C10.1601 14.0779 9.74711 14.2219 9.65811 14.2239C9.46911 14.2299 9.28711 14.1239 9.19911 13.9539C9.16511 13.8879 9.06511 13.4569 9.03311 13.2649C8.93811 12.6809 8.88911 11.7739 8.89011 10.8619C8.88911 9.90489 8.94211 8.95489 9.04811 8.37689C9.07611 8.22089 9.15811 7.86189 9.18211 7.80389C9.22711 7.69589 9.30911 7.61089 9.40811 7.55789C9.48411 7.51689 9.57111 7.49489 9.65811 7.49789C9.74711 7.49989 10.1091 7.62689 10.2331 7.67589C11.2111 8.05589 13.2801 9.43389 14.0401 10.2439C14.1081 10.3169 14.2951 10.5129 14.3261 10.5529C14.3971 10.6429 14.4321 10.7519 14.4321 10.8619C14.4321 10.9639 14.4011 11.0679 14.3371 11.1549C14.3041 11.1999 14.1131 11.3999 14.0501 11.4669Z"
                                    stroke-linecap="round" stroke-linejoin="round"/></svg> 56:36
                        </span>
                    </a>
                    <h3 class="series__title"><a href="{{ part.get_absolute_url }}">{{ part.name }}</a></h3>
                </div>
                {% endfor %}
            </div>

            <button class="section__nav section__nav--series section__nav--prev" data-nav="#series" type="button">
                <svg width="17" height="15" viewBox="0 0 17 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1.25 7.72559L16.25 7.72559" stroke-width="1.5" stroke-linecap="round"
                          stroke-linejoin="round"/>
                    <path d="M7.2998 1.70124L1.2498 7.72524L7.2998 13.7502" stroke-width="1.5" stroke-linecap="round"
                          stroke-linejoin="round"/>
                </svg>
            </button>
            <button class="section__nav section__nav--series section__nav--next" data-nav="#series" type="button">
                <svg width="17" height="15" viewBox="0 0 17 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M15.75 7.72559L0.75 7.72559" stroke-width="1.5" stroke-linecap="round"
                          stroke-linejoin="round"/>
                    <path d="M9.7002 1.70124L15.7502 7.72524L9.7002 13.7502" stroke-width="1.5" stroke-linecap="round"
                          stroke-linejoin="round"/>
                </svg>
            </button>
        </div>
    </div>
    {% endfor %}
</div>
<!-- end series -->

{% include 'movie/shared/share.html' %}