A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('panel/', include('panel.urls')),
    path('movie/', include('movie.urls')),
    path('finance/', include('finance.urls')),
    path('api/', include('api.urls')),
]

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('register/verify_account/', views.VerifyAccountView.as_view(), name='verify_account'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('forget/', views.ForgetPasswordView.as_view(), name='forget'),
    path('forget/verify/', views.ForgetPasswordVerifyView.as_view(), name='forget_verify'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]

core/urls.py
from django.urls import path

from . import views


app_name = 'core'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('privacy/', views.PrivacyView.as_view(), name='privacy'),
    path('about-us/', views.AboutUsView.as_view(), name='about'),
    path('contact-us/', views.ContactUsView.as_view(), name='contact'),
]

panel/urls.py
from django.urls import path
from . import views


app_name = 'panel'
urlpatterns = [
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('users/', views.UserListView.as_view(), name='users'),
    path('users/action/<int:pk>/', views.UserActionView.as_view(), name='user_action'),
    path('users_deleted/', views.UserDeletedListView.as_view(), name='users_deleted'),
    path('users_deleted/action/<int:pk>/', views.UserDeleteActionView.as_view(), name='user_deleted_action'),
    path('users/edit/<int:pk>/', views.UserEditView.as_view(), name='user_edit'),
    path('contacts/', views.ContactListView.as_view(), name='contacts'),
    path('contacts/action/<int:pk>/', views.ContactActionView.as_view(), name='contact_action'),
    path('movie/comments/', views.MovieCommentListView.as_view(), name='movie_comments'),
    path('movie/reviews/', views.MovieReviewListView.as_view(), name='movie_reviews'),
    path('catalog/', views.CatalogListView.as_view(), name='catalog'),
]

panel/models.py
from django.db import models

# Create your models here.

panel/forms.py
from django import forms
from django.contrib.auth import get_user_model


class UserForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'is_admin', 'role', 'username', 'email')
        widgets = {
            "first_name": forms.TextInput(attrs={"class": 'sign__input', "id": 'first_name'}),
            "last_name": forms.TextInput(attrs={"class": 'sign__input', "id": 'last_name'}),
            "username": forms.TextInput(attrs={"class": 'sign__input', "id": 'username'}),
            "email": forms.EmailInput(attrs={"class": 'sign__input', "id": 'email'}),
            "role": forms.Select(attrs={"class": 'js-example-basic-single', "id": 'rights'}),
        }

panel/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, View, UpdateView
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy

from permissions import IsRequiredAdminMixin, IsRequiredSuperuserMixin
from core.models import Contact
from .actions import user_action, contact_action, user_delete_action
from .forms import UserForm
from movie.models import MovieComment, MovieReview, Movie


class DashboardView(IsRequiredAdminMixin, TemplateView):
    template_name = 'panel/dashboard.html'


class UserListView(IsRequiredAdminMixin, ListView):
    model = get_user_model()
    template_name = 'panel/users.html'
    paginate_by = 10

    def get_context_data(self, *args, object_list=None, **kwargs):
        data = super().get_context_data(*args, object_list=None, **kwargs)
        data['count'] = self.get_queryset().count()
        return data


class UserDeletedListView(IsRequiredAdminMixin, ListView):
    model = get_user_model()
    template_name = 'panel/user_deleted.html'
    paginate_by = 10
    queryset = get_user_model().deleted.all()

    def get_context_data(self, *args, object_list=None, **kwargs):
        data = super().get_context_data(*args, object_list=object_list, **kwargs)
        data['count'] = self.get_queryset().count()
        return data


class UserDeleteActionView(IsRequiredAdminMixin, View):

    def get(self, request, pk=None):
        action = request.GET.get('action')
        user_delete_action(request, action, pk)
        return redirect('panel:users_deleted')


class UserActionView(IsRequiredAdminMixin, View):

    def get(self, request, pk=0):
        action = request.GET.get('action')
        user_action(request=request, action=action, pk=pk)
        return redirect(request.GET.get('next', 'panel:users'))


class UserEditView(IsRequiredSuperuserMixin, UpdateView):
    template_name = 'panel/edit_user.html'
    model = get_user_model()
    form_class = UserForm
    success_url = reverse_lazy('panel:users')


class ContactListView(IsRequiredAdminMixin, ListView):
    template_name = 'panel/contact.html'
    model = Contact
    queryset = Contact.objects.all().order_by('is_read')
    paginate_by = 10

    def get_context_data(self, *args, object_list=None, **kwargs):
        data = super().get_context_data(*args, object_list=None, **kwargs)
        data['count'] = self.get_queryset().count()
        return data


class ContactActionView(IsRequiredAdminMixin, View):

    def get(self, request, pk=None):
        action = self.request.GET.get('action')
        contact_action(request=request, action=action, pk=pk)
        return redirect('panel:contacts')


class MovieCommentListView(IsRequiredAdminMixin, ListView):
    model = MovieComment
    template_name = 'panel/comments.html'
    paginate_by = 15


class MovieReviewListView(IsRequiredAdminMixin, ListView):
    model = MovieReview
    template_name = 'panel/reviews.html'
    paginate_by = 15


class CatalogListView(ListView):
    model = Movie
    queryset = Movie.default_manager.all()
    template_name = 'panel/catalog.html'
    paginate_by = 15

panel/templates/panel/shared/head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- CSS -->
<link rel="stylesheet" href="https://dmitryvolkov.me/demo/flixtv/admin/css/bootstrap-reboot.min.css">
<link rel="stylesheet" href="https://dmitryvolkov.me/demo/flixtv/admin/css/bootstrap-grid.min.css">

<!-- jQuery and JS bundle w/ Popper.js -->
<script src="https://dmitryvolkov.me/demo/flixtv/admin/js/jquery-3.5.1.min.js"></script>
<script src="https://dmitryvolkov.me/demo/flixtv/admin/js/bootstrap.bundle.min.js"></script>
<link rel="stylesheet" href="{% static 'panel/css/magnific-popup.css' %}">
<link rel="stylesheet" href="{% static 'panel/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'panel/css/admin.css' %}">

<!-- Favicons -->
<link rel="icon" type="image/png" href="{% static 'panel/icon/favicon-32x32.png' %}" sizes="32x32">
<link rel="apple-touch-icon" href="icon/favicon-32x32.png">

panel/templates/panel/shared/js.html
{% load static %}

<script src="{% static 'panel/js/jquery.magnific-popup.min.js' %}"></script>
<script></script>
<script src="{% static 'panel/js/select2.min.js' %}"></script>
<script src="{% static 'panel/js/admin.js' %}"></script>

panel/templates/panel/shared/navbar.html
{% load static %}

<header class="header">
    <div class="header__content">
        <!-- header logo -->
        <a href="{% url 'panel:dashboard' %}" class="header__logo">
            <img src="{% static 'panel/img/logo.svg' %}" alt="">
        </a>
        <!-- end header logo -->

        <!-- header menu btn -->
        <button class="header__btn" type="button">
            <span></span>
            <span></span>
            <span></span>
        </button>
        <!-- end header menu btn -->
    </div>
</header>

panel/templates/panel/shared/paginator.html
<div class="col-12">
    <div class="paginator">
        <ul class="paginator__paginator">
            {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}">
                    <svg width="14" height="11" viewBox="0 0 14 11" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M13.1992 5.3645L0.75 5.3645" stroke-width="1.2" stroke-linecap="round"
                              stroke-linejoin="round"></path>
                        <path d="M8.17822 0.602051L13.1993 5.36417L8.17822 10.1271" stroke-width="1.2"
                              stroke-linecap="round" stroke-linejoin="round"></path>
                    </svg>
                </a>
            </li>
            {% endif %}

            {% for page in paginator.page_range %}
            {% if page == page_obj.number %}
            <li class="active"><a>{{ page }}</a></li>
            {% elif page > page_obj.number|add:'2' %}
            {% elif page < page_obj.number|add:'-2' %}
            {% else %}
            <li><a href="?page={{ page }}">{{ page }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}">
                    <svg width="14" height="11" viewBox="0 0 14 11" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M0.75 5.36475L13.1992 5.36475" stroke-width="1.2" stroke-linecap="round"
                              stroke-linejoin="round"></path>
                        <path d="M5.771 10.1271L0.749878 5.36496L5.771 0.602051" stroke-width="1.2"
                              stroke-linecap="round" stroke-linejoin="round"></path>
                    </svg>

                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>

panel/templates/panel/shared/sidebar.html
{% load static %}

<div class="sidebar">
    <!-- sidebar logo -->
    <a href="{% url 'panel:dashboard' %}" class="sidebar__logo">
        <img src="{% static 'panel/img/logo.svg' %}" alt="">
    </a>
    <!-- end sidebar logo -->

    <!-- sidebar user -->
    <div class="sidebar__user">
        <div class="sidebar__user-img">
            <img src="{% static 'panel/img/user.svg' %}" alt="">
        </div>

        <div class="sidebar__user-title">
            <span>{{ request.user.get_role_display }}</span>
            <p>{{ request.user.username }}</p>
        </div>

        <a href="{% url 'accounts:logout' %}" class="sidebar__user-btn" type="button">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M4,12a1,1,0,0,0,1,1h7.59l-2.3,2.29a1,1,0,0,0,0,1.42,1,1,0,0,0,1.42,0l4-4a1,1,0,0,0,.21-.33,1,1,0,0,0,0-.76,1,1,0,0,0-.21-.33l-4-4a1,1,0,1,0-1.42,1.42L12.59,11H5A1,1,0,0,0,4,12ZM17,2H7A3,3,0,0,0,4,5V8A1,1,0,0,0,6,8V5A1,1,0,0,1,7,4H17a1,1,0,0,1,1,1V19a1,1,0,0,1-1,1H7a1,1,0,0,1-1-1V16a1,1,0,0,0-2,0v3a3,3,0,0,0,3,3H17a3,3,0,0,0,3-3V5A3,3,0,0,0,17,2Z"/>
            </svg>
        </a>
    </div>
    <!-- end sidebar user -->

    <!-- sidebar nav -->
    <ul class="sidebar__nav">
        <li class="sidebar__nav-item">
            <a href="{% url 'panel:dashboard' %}"
               class="sidebar__nav-link {% if request.path == '/panel/dashboard/' %}sidebar__nav-link--active{% endif %}">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="M20,8h0L14,2.74a3,3,0,0,0-4,0L4,8a3,3,0,0,0-1,2.26V19a3,3,0,0,0,3,3H18a3,3,0,0,0,3-3V10.25A3,3,0,0,0,20,8ZM14,20H10V15a1,1,0,0,1,1-1h2a1,1,0,0,1,1,1Zm5-1a1,1,0,0,1-1,1H16V15a3,3,0,0,0-3-3H11a3,3,0,0,0-3,3v5H6a1,1,0,0,1-1-1V10.25a1,1,0,0,1,.34-.75l6-5.25a1,1,0,0,1,1.32,0l6,5.25a1,1,0,0,1,.34.75Z"/>
                </svg>
                <span>داشبورد</span></a>
        </li>

        <li class="sidebar__nav-item">
            <a href="{% url 'panel:catalog' %}"
               class="sidebar__nav-link {% if request.path == '/panel/catalog/' %}sidebar__nav-link--active{% endif %}">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="M10,13H3a1,1,0,0,0-1,1v7a1,1,0,0,0,1,1h7a1,1,0,0,0,1-1V14A1,1,0,0,0,10,13ZM9,20H4V15H9ZM21,2H14a1,1,0,0,0-1,1v7a1,1,0,0,0,1,1h7a1,1,0,0,0,1-1V3A1,1,0,0,0,21,2ZM20,9H15V4h5Zm1,4H14a1,1,0,0,0-1,1v7a1,1,0,0,0,1,1h7a1,1,0,0,0,1-1V14A1,1,0,0,0,21,13Zm-1,7H15V15h5ZM10,2H3A1,1,0,0,0,2,3v7a1,1,0,0,0,1,1h7a1,1,0,0,0,1-1V3A1,1,0,0,0,10,2ZM9,9H4V4H9Z"/>
                </svg>
                <span>کاتالوگ</span></a>
        </li>

        <!-- collapse -->
        <li class="sidebar__nav-item">
            <a class="sidebar__nav-link" data-toggle="collapse" href="#collapseMenu" role="button" aria-expanded="false"
               aria-controls="collapseMenu">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="M19,5.5H12.72l-.32-1a3,3,0,0,0-2.84-2H5a3,3,0,0,0-3,3v13a3,3,0,0,0,3,3H19a3,3,0,0,0,3-3V8.5A3,3,0,0,0,19,5.5Zm1,13a1,1,0,0,1-1,1H5a1,1,0,0,1-1-1V5.5a1,1,0,0,1,1-1H9.56a1,1,0,0,1,.95.68l.54,1.64A1,1,0,0,0,12,7.5h7a1,1,0,0,1,1,1Z"/>
                </svg>
                <span>صفحات</span>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="M17,9.17a1,1,0,0,0-1.41,0L12,12.71,8.46,9.17a1,1,0,0,0-1.41,0,1,1,0,0,0,0,1.42l4.24,4.24a1,1,0,0,0,1.42,0L17,10.59A1,1,0,0,0,17,9.17Z"/>
                </svg>
            </a>

            <ul class="collapse sidebar__menu" id="collapseMenu">
                <li><a href="{% url 'panel:contacts' %}">تماس ها</a></li>
            </ul>
        </li>
        <!-- end collapse -->

        <li class="sidebar__nav-item">
            <a href="{% url 'panel:users' %}"
               class="sidebar__nav-link {% if request.path == '/panel/users/' %}sidebar__nav-link--active{% endif %}">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="M12.3,12.22A4.92,4.92,0,0,0,14,8.5a5,5,0,0,0-10,0,4.92,4.92,0,0,0,1.7,3.72A8,8,0,0,0,1,19.5a1,1,0,0,0,2,0,6,6,0,0,1,12,0,1,1,0,0,0,2,0A8,8,0,0,0,12.3,12.22ZM9,11.5a3,3,0,1,1,3-3A3,3,0,0,1,9,11.5Zm9.74.32A5,5,0,0,0,15,3.5a1,1,0,0,0,0,2,3,3,0,0,1,3,3,3,3,0,0,1-1.5,2.59,1,1,0,0,0-.5.84,1,1,0,0,0,.45.86l.39.26.13.07a7,7,0,0,1,4,6.38,1,1,0,0,0,2,0A9,9,0,0,0,18.74,11.82Z"/>
                </svg>
                <span>کاربران</span></a>
        </li>
        <li class="sidebar__nav-item">
            <a href="{% url 'panel:users_deleted' %}"
               class="sidebar__nav-link {% if request.path == '/panel/users_deleted/' %}sidebar__nav-link--active{% endif %}">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="M12.3,12.22A4.92,4.92,0,0,0,14,8.5a5,5,0,0,0-10,0,4.92,4.92,0,0,0,1.7,3.72A8,8,0,0,0,1,19.5a1,1,0,0,0,2,0,6,6,0,0,1,12,0,1,1,0,0,0,2,0A8,8,0,0,0,12.3,12.22ZM9,11.5a3,3,0,1,1,3-3A3,3,0,0,1,9,11.5Zm9.74.32A5,5,0,0,0,15,3.5a1,1,0,0,0,0,2,3,3,0,0,1,3,3,3,3,0,0,1-1.5,2.59,1,1,0,0,0-.5.84,1,1,0,0,0,.45.86l.39.26.13.07a7,7,0,0,1,4,6.38,1,1,0,0,0,2,0A9,9,0,0,0,18.74,11.82Z"/>
                </svg>
                <span>کاربران حذف شده</span></a>
        </li>
        <li class="sidebar__nav-item">
            <a href="{% url 'panel:movie_comments' %}" class="sidebar__nav-link">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="M8,11a1,1,0,1,0,1,1A1,1,0,0,0,8,11Zm4,0a1,1,0,1,0,1,1A1,1,0,0,0,12,11Zm4,0a1,1,0,1,0,1,1A1,1,0,0,0,16,11ZM12,2A10,10,0,0,0,2,12a9.89,9.89,0,0,0,2.26,6.33l-2,2a1,1,0,0,0-.21,1.09A1,1,0,0,0,3,22h9A10,10,0,0,0,12,2Zm0,18H5.41l.93-.93a1,1,0,0,0,.3-.71,1,1,0,0,0-.3-.7A8,8,0,1,1,12,20Z"></path>
                </svg>
                <span>نظرات</span></a>
        </li>
        <li class="sidebar__nav-item">
				<a href="{% url 'panel:movie_reviews' %}" class="sidebar__nav-link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,9.67A1,1,0,0,0,21.14,9l-5.69-.83L12.9,3a1,1,0,0,0-1.8,0L8.55,8.16,2.86,9a1,1,0,0,0-.81.68,1,1,0,0,0,.25,1l4.13,4-1,5.68A1,1,0,0,0,6.9,21.44L12,18.77l5.1,2.67a.93.93,0,0,0,.46.12,1,1,0,0,0,.59-.19,1,1,0,0,0,.4-1l-1-5.68,4.13-4A1,1,0,0,0,22,9.67Zm-6.15,4a1,1,0,0,0-.29.88l.72,4.2-3.76-2a1.06,1.06,0,0,0-.94,0l-3.76,2,.72-4.2a1,1,0,0,0-.29-.88l-3-3,4.21-.61a1,1,0,0,0,.76-.55L12,5.7l1.88,3.82a1,1,0,0,0,.76.55l4.21.61Z"></path></svg> <span>امتیازات</span></a>
        </li>
        <li class="sidebar__nav-item">
            <a href="{% url 'core:home' %}" class="sidebar__nav-link">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="M17,11H9.41l3.3-3.29a1,1,0,1,0-1.42-1.42l-5,5a1,1,0,0,0-.21.33,1,1,0,0,0,0,.76,1,1,0,0,0,.21.33l5,5a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42L9.41,13H17a1,1,0,0,0,0-2Z"/>
                </svg>
                <span>برگرشتن به سایت</span></a>
        </li>
    </ul>
    <!-- end sidebar nav -->

    <!-- sidebar copyright -->
    <div class="sidebar__copyright">© فارسی سازی و راستچین <br>توسط <a
            href="https://www.rtl-theme.com/author/tirtashirika/" target="_blank">تیرتاشی ریکا</a></div>
    <!-- end sidebar copyright -->
</div>