A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('panel/', include('panel.urls')),
    path('movie/', include('movie.urls')),
    path('finance/', include('finance.urls')),
    path('api/', include('api.urls')),
]

panel/urls.py
from django.urls import path
from . import views


app_name = 'panel'
urlpatterns = [
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('users/', views.UserListView.as_view(), name='users'),
    path('users/action/<int:pk>/', views.UserActionView.as_view(), name='user_action'),
    path('users_deleted/', views.UserDeletedListView.as_view(), name='users_deleted'),
    path('users_deleted/action/<int:pk>/', views.UserDeleteActionView.as_view(), name='user_deleted_action'),
    path('users/edit/<int:pk>/', views.UserEditView.as_view(), name='user_edit'),
    path('contacts/', views.ContactListView.as_view(), name='contacts'),
    path('contacts/action/<int:pk>/', views.ContactActionView.as_view(), name='contact_action'),
    path('movie/comments/', views.MovieCommentListView.as_view(), name='movie_comments'),
    path('movie/reviews/', views.MovieReviewListView.as_view(), name='movie_reviews'),
    path('catalog/', views.CatalogListView.as_view(), name='catalog'),
]

movie/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.db.models import Avg, Sum, Count

from .choices import TYPE_CHOICES, QUALITY_CHOICES, COUNTRY_CHOICES, IRAN
from .managers import IsActiveManager, MovieManager, MovieCommentManager


class BaseMovieModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Genre(models.Model):
    name = models.CharField(max_length=32, verbose_name=_('name'))
    english_name = models.CharField(max_length=32, verbose_name=_('english name'))
    slug = models.SlugField(max_length=40, verbose_name=_('slug'))
    image_cover = models.ImageField(verbose_name=_('image'))

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/movie/category/?genre={self.slug}'


class Movie(BaseMovieModel):
    name = models.CharField(max_length=120, verbose_name=_('name'))
    english_name = models.CharField(max_length=120, verbose_name=_('english name'))
    slug = models.SlugField(max_length=120, verbose_name=_('slug'), db_index=True)
    description = models.TextField(verbose_name=_('description'))
    poster = models.ImageField(verbose_name='poster', null=True, blank=True)
    image_cover = models.ImageField(verbose_name=_('image cover'))
    image_background = models.ImageField(verbose_name=_('image background'))
    publish_at = models.DateField(verbose_name=_('publish_at'))
    created_at = models.DateField(verbose_name=_('created at'))
    trailer = models.CharField(max_length=240, verbose_name=_('trailer'), null=True, blank=True)
    type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES, default=1, verbose_name=_('type'))
    quality = models.PositiveSmallIntegerField(choices=QUALITY_CHOICES, default=1, verbose_name=_('quality'))
    time_in_minutes = models.PositiveIntegerField(verbose_name=_('time in minutes'))
    ages = models.PositiveSmallIntegerField(verbose_name=_('ages'))
    is_free = models.BooleanField(default=True, verbose_name=_('is free'))
    country = models.CharField(max_length=34, choices=COUNTRY_CHOICES, verbose_name=_('country'))
    is_active = models.BooleanField(default=True)

    default_manager = models.Manager()
    objects = MovieManager()

    class Meta:
        verbose_name = _('Movie')
        verbose_name_plural = _('Movies')
        ordering = ('-publish_at',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('movie:detail', args=[self.slug])

    def get_comments(self):
        return self.comments.filter(is_active=True)

    def get_comment_count(self):
        return self.comments.filter(is_active=True).count()

    def get_reviews(self):
        return self.reviews.filter(is_active=True)

    def get_review_count(self):
        return self.reviews.filter(is_active=True).count()

    def get_avg_rate(self):
        rate = self.reviews.all().aggregate(avg_rate=Avg('rate'))
        if rate['avg_rate']:
            return round(rate['avg_rate'], 1)
        return 8

    @classmethod
    def get_favorites(cls):
        return cls.objects.all().annotate(favorite_count=Count('favorites')).order_by('-favorite_count')[:12]

    @classmethod
    def get_all_favorites(cls):
        return cls.objects.all().annotate(favorite_count=Count('favorites')).order_by('-favorite_count')

    @classmethod
    def get_news(cls):
        return cls.objects.all()[:12]

    @classmethod
    def get_best_rates(cls):
        return cls.default_manager.all().annotate(avg_rate=Sum('reviews__rate')).order_by('-avg_rate')

    @classmethod
    def get_recommend_movie(cls, user):
        genres = user.get_favorite_genres()
        return cls.objects.filter(genres__genre__id__in=genres).distinct()[:5]

    def get_genres(self):
        return self.genres.all()

    def get_similar_movies(self):
        return Movie.objects.filter(genres__genre_id__in=self.genres.all().values('genre__id')).distinct()[:12]


class MovieGenre(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='genres', verbose_name=_('movie'))
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='movies', verbose_name=_('genre'))

    def __str__(self):
        return f'{self.movie}-{self.genre}'


class FilmMovie(Movie):

    class Meta:
        proxy = True


class SeriesMovie(Movie):
    class Meta:
        proxy = True


class FilmLink(BaseMovieModel):
    film = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='links')
    name = models.CharField(max_length=120)
    quality = models.IntegerField(verbose_name=_('quality'))
    volume = models.CharField(max_length=32)
    link = models.CharField(max_length=240)

    class Meta:
        verbose_name = _('Film Link')
        verbose_name_plural = _('Film Links')
        ordering = ('-quality',)

    def __str__(self):
        return f'{self.film.name[:32]}---{self.name}'


class FilmSubtitle(models.Model):
    film = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='subtitles', verbose_name=_('film'))
    language = models.CharField(max_length=32, choices=COUNTRY_CHOICES, default=IRAN, verbose_name=_('language'))
    subtitle = models.FileField(max_length=240, verbose_name=_('subtitle'))

    def __str__(self):
        return f'{self.film}-{self.language}'


class SeriesSeason(BaseMovieModel):
    series = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='seasons', verbose_name=_('series'))
    season = models.PositiveSmallIntegerField(verbose_name=_('season'))
    name = models.CharField(max_length=120)
    image_background = models.ImageField(verbose_name=_('image background'))

    class Meta:
        verbose_name = _('Series Season')
        verbose_name_plural = _('Series Seasons')
        ordering = ('season',)

    def __str__(self):
        return f'series name: {self.series.name[:32]} -- season: {self.season}'


class SeasonPart(BaseMovieModel):
    season = models.ForeignKey(SeriesSeason, on_delete=models.CASCADE, related_name='parts',
                               verbose_name=_('Season Part'))
    name = models.CharField(max_length=64, verbose_name=_('name'))
    poster = models.ImageField(verbose_name=_('poster'))
    # TODO: below is true and up is false
    # image_cover = models.ImageField(verbose_name=_('image cover'))
    part = models.PositiveSmallIntegerField(verbose_name=_('part'))

    class Meta:
        verbose_name = _('Season Part')
        verbose_name_plural = _('Season Parts')
        ordering = ('part',)

    def __str__(self):
        return f'{self.season} -- part: {self.part}'

    def get_absolute_url(self):
        return reverse('movie:part_detail', args=[self.pk, self.season.series.slug])


class SeasonPartSubtitle(models.Model):
    season_part = models.ForeignKey(SeasonPart,
                                    on_delete=models.CASCADE, related_name='subtitles', verbose_name=_('season part'))
    language = models.CharField(max_length=32, choices=COUNTRY_CHOICES, default=IRAN, verbose_name=_('language'))
    subtitle = models.FileField(max_length=240, verbose_name=_('subtitle'))

    def __str__(self):
        return f'{self.season_part}-{self.language}'


class PartLink(BaseMovieModel):
    season_part = models.ForeignKey(SeasonPart, on_delete=models.CASCADE, related_name='links',
                                    verbose_name=_('part link'))
    name = models.CharField(max_length=64, verbose_name=_('name'))
    quality = models.IntegerField(verbose_name=_('quality'))
    volume = models.CharField(max_length=34)
    link = models.CharField(max_length=240)

    class Meta:
        verbose_name = _('Part Link')
        verbose_name_plural = _('Part Links')
        ordering = ('-quality',)

    def __str__(self):
        return f'{self.season_part} -- quality: {self.quality}'


class MovieComment(BaseMovieModel):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comments',
                             verbose_name=_('user'))
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='comments', verbose_name=_('movie'))
    body = models.TextField(verbose_name=_('body'))
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children',
                               verbose_name=_('parent'), null=True, blank=True)
    is_reply = models.BooleanField(default=False, verbose_name=_('is reply'))
    is_read = models.BooleanField(default=False, verbose_name=_('is read'))
    is_active = models.BooleanField(default=False, verbose_name=_('is active'))

    default_manager = models.Manager()
    objects = MovieCommentManager()

    class Meta:
        verbose_name = _('Movie Comment')
        verbose_name_plural = _('Movie Comments')
        ordering = ('-created',)

    def __str__(self):
        return f'{self.user} - {self.movie}'


class MovieReview(BaseMovieModel):
    RATE_CHOICES = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10),
    )
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='reviews',
                             verbose_name=_('user'))
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews', verbose_name=_('movie'))
    rate = models.PositiveSmallIntegerField(choices=RATE_CHOICES, verbose_name=_('rate'))
    subject = models.CharField(max_length=120, verbose_name=_('subject'))
    description = models.TextField(verbose_name=_('body'))
    is_read = models.BooleanField(default=False, verbose_name=_('is read'))
    is_active = models.BooleanField(default=False, verbose_name=_('is active'))

panel/models.py
from django.db import models

# Create your models here.

panel/forms.py
from django import forms
from django.contrib.auth import get_user_model


class UserForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'is_admin', 'role', 'username', 'email')
        widgets = {
            "first_name": forms.TextInput(attrs={"class": 'sign__input', "id": 'first_name'}),
            "last_name": forms.TextInput(attrs={"class": 'sign__input', "id": 'last_name'}),
            "username": forms.TextInput(attrs={"class": 'sign__input', "id": 'username'}),
            "email": forms.EmailInput(attrs={"class": 'sign__input', "id": 'email'}),
            "role": forms.Select(attrs={"class": 'js-example-basic-single', "id": 'rights'}),
        }

panel/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, View, UpdateView
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy

from permissions import IsRequiredAdminMixin, IsRequiredSuperuserMixin
from core.models import Contact
from .actions import user_action, contact_action, user_delete_action
from .forms import UserForm
from movie.models import MovieComment, MovieReview, Movie


class DashboardView(IsRequiredAdminMixin, TemplateView):
    template_name = 'panel/dashboard.html'


class UserListView(IsRequiredAdminMixin, ListView):
    model = get_user_model()
    template_name = 'panel/users.html'
    paginate_by = 10

    def get_context_data(self, *args, object_list=None, **kwargs):
        data = super().get_context_data(*args, object_list=None, **kwargs)
        data['count'] = self.get_queryset().count()
        return data


class UserDeletedListView(IsRequiredAdminMixin, ListView):
    model = get_user_model()
    template_name = 'panel/user_deleted.html'
    paginate_by = 10
    queryset = get_user_model().deleted.all()

    def get_context_data(self, *args, object_list=None, **kwargs):
        data = super().get_context_data(*args, object_list=object_list, **kwargs)
        data['count'] = self.get_queryset().count()
        return data


class UserDeleteActionView(IsRequiredAdminMixin, View):

    def get(self, request, pk=None):
        action = request.GET.get('action')
        user_delete_action(request, action, pk)
        return redirect('panel:users_deleted')


class UserActionView(IsRequiredAdminMixin, View):

    def get(self, request, pk=0):
        action = request.GET.get('action')
        user_action(request=request, action=action, pk=pk)
        return redirect(request.GET.get('next', 'panel:users'))


class UserEditView(IsRequiredSuperuserMixin, UpdateView):
    template_name = 'panel/edit_user.html'
    model = get_user_model()
    form_class = UserForm
    success_url = reverse_lazy('panel:users')


class ContactListView(IsRequiredAdminMixin, ListView):
    template_name = 'panel/contact.html'
    model = Contact
    queryset = Contact.objects.all().order_by('is_read')
    paginate_by = 10

    def get_context_data(self, *args, object_list=None, **kwargs):
        data = super().get_context_data(*args, object_list=None, **kwargs)
        data['count'] = self.get_queryset().count()
        return data


class ContactActionView(IsRequiredAdminMixin, View):

    def get(self, request, pk=None):
        action = self.request.GET.get('action')
        contact_action(request=request, action=action, pk=pk)
        return redirect('panel:contacts')


class MovieCommentListView(IsRequiredAdminMixin, ListView):
    model = MovieComment
    template_name = 'panel/comments.html'
    paginate_by = 15


class MovieReviewListView(IsRequiredAdminMixin, ListView):
    model = MovieReview
    template_name = 'panel/reviews.html'
    paginate_by = 15


class CatalogListView(ListView):
    model = Movie
    queryset = Movie.default_manager.all()
    template_name = 'panel/catalog.html'
    paginate_by = 15

panel/templates/panel/user_deleted.html
{% extends 'panel/base.html' %}

{% load static %}

{% block title %}لیست کاربران وب سایت{% endblock %}

{% block content %}
	<!-- main content -->
	<main class="main">
		<div class="container-fluid">
			<div class="row">
				<!-- main title -->
				<div class="col-12">
					<div class="main__title">
						<h2>کاربران</h2>

						<span class="main__title-stat">تعداد {{ count|floatformat:"-3g" }}</span>

						<div class="main__title-wrap">
							<!-- filter sort -->
							<div class="filter" id="filter__sort">
								<span class="filter__item-label">مرتب بر اساس :</span>

								<div class="filter__item-btn dropdown-toggle" role="navigation" id="filter-sort" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<input type="button" value="تاریخ ایجاد شده">
									<span></span>
								</div>

								<ul class="filter__item-menu dropdown-menu scrollbar-dropdown" aria-labelledby="filter-sort">
									<li>تاریخ ایجاد شده</li>
									<li>پلن اشتراک</li>
									<li>وضعیت</li>
								</ul>
							</div>
							<!-- end filter sort -->

							<!-- search -->
							<form action="#" class="main__title-form">
								<input type="text" placeholder="دنبال کاربر . .">
								<button type="button">
									<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="8.25998" cy="8.25995" r="7.48191" stroke="#2F80ED" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></circle><path d="M13.4637 13.8523L16.3971 16.778" stroke="#2F80ED" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>
								</button>
							</form>
							<!-- end search -->
						</div>
					</div>
				</div>
				<!-- end main title -->

				<!-- users -->
				<div class="col-12">
					<div class="main__table-wrap">
						<table class="main__table">
							<thead>
								<tr>
									<th>شناسه</th>
									<th>اطلاعات پایه</th>
									<th>نام کاربری</th>
									<th>پلن اشتراک</th>
									<th>نظرات</th>
									<th>وضعیت</th>
									<th>تاریخ ایجاد شده</th>
									<th>اقدامات</th>
								</tr>
							</thead>

							<tbody>
							{% for user in object_list %}
								<tr>
									<td>
										<div class="main__table-text">{{ user.id }}</div>
									</td>
									<td>
										<div class="main__user">
											<div class="main__avatar">
												<img src="{% static 'panel/img/user.svg' %}" alt="">
											</div>
											<div class="main__meta">
												<h3>{{ user.username }}</h3>
												<span>{{ user.email }}</span>
											</div>
										</div>
									</td>
									<td>
										<div class="main__table-text">{{ user.username }}</div>
									</td>
									<td>
										<div class="main__table-text">حرفه ای</div>
									</td>
									<td>
										<div class="main__table-text">13</div>
									</td>
									{% if user.is_active %}
									<td>
										<div class="main__table-text main__table-text--green">تایید شده</div>
									</td>
									{% else %}
									<td>
										<div class="main__table-text main__table-text--red">مسدود</div>
									</td>
									{% endif %}
									<td>
										<div class="main__table-text">13 / 02 / 1400</div>
									</td>
									<td>
										<div class="main__table-btns">
											<a href="{% url 'panel:user_deleted_action' user.id %}">برگرداندن</a>
										</div>
									</td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
				<!-- end users -->

				<!-- paginator -->
				{% include 'panel/shared/paginator.html' %}
				<!-- end paginator -->
			</div>
		</div>
	</main>
	<!-- end main content -->

	<!-- modal status -->
	<div id="modal-status" class="zoom-anim-dialog mfp-hide modal">
		<h6 class="modal__title">تغییر وضعیت</h6>

		<p class="modal__text">آیا مطمئن هستید که وضعیت را تغییر می دهید؟</p>

		<div class="modal__btns">
			<a href="" id="change-status" class="modal__btn modal__btn--apply" type="button">اعمال</a>
			<a class="modal__btn modal__btn--dismiss" type="button">لغو</a>
		</div>
	</div>
	<!-- end modal status -->

	<!-- modal delete -->
	<div id="modal-delete" class="zoom-anim-dialog mfp-hide modal">
		<h6 class="modal__title">حذف کاربر</h6>

		<p class="modal__text">آیا مطمئن هستید که این کاربر را برای همیشه حذف می کنید؟</p>

		<div class="modal__btns">
			<button class="modal__btn modal__btn--apply" type="button">حذف</button>
			<button class="modal__btn modal__btn--dismiss" type="button">لغو</button>
		</div>
	</div>
	<!-- end modal delete -->

{% endblock %}

panel/templates/panel/users.html
{% extends 'panel/base.html' %}

{% load static %}

{% block title %}لیست کاربران وب سایت{% endblock %}

{% block content %}
	<!-- main content -->
	<main class="main">
		<div class="container-fluid">
			<div class="row">
				<!-- main title -->
				<div class="col-12">
					<div class="main__title">
						<h2>کاربران</h2>

						<span class="main__title-stat">تعداد {{ count|floatformat:"-3g" }}</span>

						<div class="main__title-wrap">
							<!-- filter sort -->
							<div class="filter" id="filter__sort">
								<span class="filter__item-label">مرتب بر اساس :</span>

								<div class="filter__item-btn dropdown-toggle" role="navigation" id="filter-sort" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<input type="button" value="تاریخ ایجاد شده">
									<span></span>
								</div>

								<ul class="filter__item-menu dropdown-menu scrollbar-dropdown" aria-labelledby="filter-sort">
									<li>تاریخ ایجاد شده</li>
									<li>پلن اشتراک</li>
									<li>وضعیت</li>
								</ul>
							</div>
							<!-- end filter sort -->

							<!-- search -->
							<form action="#" class="main__title-form">
								<input type="text" placeholder="دنبال کاربر . .">
								<button type="button">
									<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="8.25998" cy="8.25995" r="7.48191" stroke="#2F80ED" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></circle><path d="M13.4637 13.8523L16.3971 16.778" stroke="#2F80ED" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>
								</button>
							</form>
							<!-- end search -->
						</div>
					</div>
				</div>
				<!-- end main title -->

				<!-- users -->
				<div class="col-12">
					<div class="main__table-wrap">
						<table class="main__table">
							<thead>
								<tr>
									<th>شناسه</th>
									<th>اطلاعات پایه</th>
									<th>نام کاربری</th>
									<th>پلن اشتراک</th>
									<th>نظرات</th>
									<th>وضعیت</th>
									<th>تاریخ ایجاد شده</th>
									<th>اقدامات</th>
								</tr>
							</thead>

							<tbody>
							{% for user in object_list %}
								<tr>
									<td>
										<div class="main__table-text">{{ user.id }}</div>
									</td>
									<td>
										<div class="main__user">
											<div class="main__avatar">
												<img src="{% static 'panel/img/user.svg' %}" alt="">
											</div>
											<div class="main__meta">
												<h3>{{ user.username }}</h3>
												<span>{{ user.email }}</span>
											</div>
										</div>
									</td>
									<td>
										<div class="main__table-text">{{ user.username }}</div>
									</td>
									<td>
										<div class="main__table-text">حرفه ای</div>
									</td>
									<td>
										<div class="main__table-text">13</div>
									</td>
									{% if user.is_active %}
									<td>
										<div class="main__table-text main__table-text--green">تایید شده</div>
									</td>
									{% else %}
									<td>
										<div class="main__table-text main__table-text--red">مسدود</div>
									</td>
									{% endif %}
									<td>
										<div class="main__table-text">13 / 02 / 1400</div>
									</td>
									<td>
										<div class="main__table-btns">
											<a href="{% url 'panel:user_action' user.id %}?next=/panel/users/&action=change_status" class="main__table-btn main__table-btn--banned open-model">
												<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12,13a1.49,1.49,0,0,0-1,2.61V17a1,1,0,0,0,2,0V15.61A1.49,1.49,0,0,0,12,13Zm5-4V7A5,5,0,0,0,7,7V9a3,3,0,0,0-3,3v7a3,3,0,0,0,3,3H17a3,3,0,0,0,3-3V12A3,3,0,0,0,17,9ZM9,7a3,3,0,0,1,6,0V9H9Zm9,12a1,1,0,0,1-1,1H7a1,1,0,0,1-1-1V12a1,1,0,0,1,1-1H17a1,1,0,0,1,1,1Z"/></svg>
											</a>
											<a href="{% url 'panel:user_edit' user.id %}" class="main__table-btn main__table-btn--edit">
												<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,7.24a1,1,0,0,0-.29-.71L17.47,2.29A1,1,0,0,0,16.76,2a1,1,0,0,0-.71.29L13.22,5.12h0L2.29,16.05a1,1,0,0,0-.29.71V21a1,1,0,0,0,1,1H7.24A1,1,0,0,0,8,21.71L18.87,10.78h0L21.71,8a1.19,1.19,0,0,0,.22-.33,1,1,0,0,0,0-.24.7.7,0,0,0,0-.14ZM6.83,20H4V17.17l9.93-9.93,2.83,2.83ZM18.17,8.66,15.34,5.83l1.42-1.41,2.82,2.82Z"/></svg>
											</a>
											<a href="{% url 'panel:user_action' user.id %}?next=/panel/users/&action=delete" class="main__table-btn main__table-btn--delete">
												<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M10,18a1,1,0,0,0,1-1V11a1,1,0,0,0-2,0v6A1,1,0,0,0,10,18ZM20,6H16V5a3,3,0,0,0-3-3H11A3,3,0,0,0,8,5V6H4A1,1,0,0,0,4,8H5V19a3,3,0,0,0,3,3h8a3,3,0,0,0,3-3V8h1a1,1,0,0,0,0-2ZM10,5a1,1,0,0,1,1-1h2a1,1,0,0,1,1,1V6H10Zm7,14a1,1,0,0,1-1,1H8a1,1,0,0,1-1-1V8H17Zm-3-1a1,1,0,0,0,1-1V11a1,1,0,0,0-2,0v6A1,1,0,0,0,14,18Z"/></svg>
											</a>
										</div>
									</td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
				<!-- end users -->

				<!-- paginator -->
				{% include 'panel/shared/paginator.html' %}
				<!-- end paginator -->
			</div>
		</div>
	</main>
	<!-- end main content -->

	<!-- modal status -->
	<div id="modal-status" class="zoom-anim-dialog mfp-hide modal">
		<h6 class="modal__title">تغییر وضعیت</h6>

		<p class="modal__text">آیا مطمئن هستید که وضعیت را تغییر می دهید؟</p>

		<div class="modal__btns">
			<a href="" id="change-status" class="modal__btn modal__btn--apply" type="button">اعمال</a>
			<a class="modal__btn modal__btn--dismiss" type="button">لغو</a>
		</div>
	</div>
	<!-- end modal status -->

	<!-- modal delete -->
	<div id="modal-delete" class="zoom-anim-dialog mfp-hide modal">
		<h6 class="modal__title">حذف کاربر</h6>

		<p class="modal__text">آیا مطمئن هستید که این کاربر را برای همیشه حذف می کنید؟</p>

		<div class="modal__btns">
			<button class="modal__btn modal__btn--apply" type="button">حذف</button>
			<button class="modal__btn modal__btn--dismiss" type="button">لغو</button>
		</div>
	</div>
	<!-- end modal delete -->

{% endblock %}