A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('panel/', include('panel.urls')),
    path('movie/', include('movie.urls')),
    path('finance/', include('finance.urls')),
    path('api/', include('api.urls')),
]

core/urls.py
from django.urls import path

from . import views


app_name = 'core'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('privacy/', views.PrivacyView.as_view(), name='privacy'),
    path('about-us/', views.AboutUsView.as_view(), name='about'),
    path('contact-us/', views.ContactUsView.as_view(), name='contact'),
]

finance/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views


app_name = 'finance'
urlpatterns = [
    path('plan/', TemplateView.as_view(template_name='finance/plan.html'), name='plan'),
    path('plan/pay/', views.PlanPayView.as_view(), name='pay_plan'),
    path('plan/verify/', views.PlanPayVerify.as_view(), name='pay_verify'),
]

movie/urls.py
from django.urls import path

from . import views


app_name = 'movie'

urlpatterns = [
    path('detail/<slug:slug>/', views.MovieDetailView.as_view(), name='detail'),
    path('part_detail/<int:pk>/<slug:slug>/', views.PartDetailSeasonView.as_view(), name='part_detail'),
    path('favorite/<int:pk>/', views.MovieFavoriteAction.as_view(), name='favorite'),
    path('catalogue/', views.MovieCatalogueView.as_view(), name='catalogue'),
    path('category/', views.MovieCategoryView.as_view(), name='category'),
]

panel/urls.py
from django.urls import path
from . import views


app_name = 'panel'
urlpatterns = [
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('users/', views.UserListView.as_view(), name='users'),
    path('users/action/<int:pk>/', views.UserActionView.as_view(), name='user_action'),
    path('users_deleted/', views.UserDeletedListView.as_view(), name='users_deleted'),
    path('users_deleted/action/<int:pk>/', views.UserDeleteActionView.as_view(), name='user_deleted_action'),
    path('users/edit/<int:pk>/', views.UserEditView.as_view(), name='user_edit'),
    path('contacts/', views.ContactListView.as_view(), name='contacts'),
    path('contacts/action/<int:pk>/', views.ContactActionView.as_view(), name='contact_action'),
    path('movie/comments/', views.MovieCommentListView.as_view(), name='movie_comments'),
    path('movie/reviews/', views.MovieReviewListView.as_view(), name='movie_reviews'),
    path('catalog/', views.CatalogListView.as_view(), name='catalog'),
]

templates/shared/head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/slider-radio.css' %}">
<link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
<link rel="stylesheet" href="{% static 'css/plyr.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">

<!-- Favicons -->
<link rel="icon" type="image/png" href="{% static 'icon/favicon-32x32.png' %}" sizes="32x32">
<link rel="apple-touch-icon" href="{% static 'icon/favicon-32x32.png' %}">

templates/shared/js.html
{% load static %}

<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/slider-radio.js' %}"></script>
<script src="{% static 'js/select2.min.js' %}"></script>
<script></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/plyr.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

templates/shared/navbar.html
{% load static %}

<!-- header (relative style) -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="header__content">
                <button class="header__menu" type="button">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>

                <a href="{% url 'core:home' %}" class="header__logo">
                    <img src="{% static 'img/logo.svg' %}" alt="جنگو مووی، فیلم و سریال روز دنیا">
                </a>

                <ul class="header__nav">
                    <li class="header__nav-item">
                        <a class="header__nav-link" href="{% url 'core:home' %}">صفحه اصلی</a>
                    </li>
                    <li class="header__nav-item">
                        <a class="header__nav-link" href="{% url 'movie:catalogue' %}">کاتالوگ</a>
                    </li>
                    <li class="header__nav-item">
                        <a class="header__nav-link" href="{% url 'finance:plan' %}">خرید اشتراک</a>
                    </li>
                    {% if request.user.is_staff %}
                    <li class="header__nav-item">
                        <a class="header__nav-link" href="{% url 'panel:dashboard' %}">پنل مدریت</a>
                    </li>
                    {% endif %}
                    <li class="header__nav-item">
                        <a class="header__nav-link header__nav-link--more" href="#" role="button" id="dropdownMenu3"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <svg width="25" height="25" viewBox="0 0 25 25" fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path d="M6.93893 14.3033C6.08141 14.3033 5.38477 13.6067 5.38477 12.7505C5.38477 11.8943 6.08141 11.1963 6.93893 11.1963C7.79644 11.1963 8.49309 11.8943 8.49309 12.7505C8.49309 13.6067 7.79644 14.3033 6.93893 14.3033Z"/>
                                <path d="M12.7501 14.3033C11.8926 14.3033 11.1959 13.6067 11.1959 12.7505C11.1959 11.8943 11.8926 11.1963 12.7501 11.1963C13.6076 11.1963 14.3042 11.8943 14.3042 12.7505C14.3042 13.6067 13.6076 14.3033 12.7501 14.3033Z"/>
                                <path d="M18.5608 14.3033C17.7032 14.3033 17.0066 13.6067 17.0066 12.7505C17.0066 11.8943 17.7032 11.1963 18.5608 11.1963C19.4183 11.1963 20.1149 11.8943 20.1149 12.7505C20.1149 13.6067 19.4183 14.3033 18.5608 14.3033Z"/>
                            </svg>
                        </a>

                        <ul class="dropdown-menu header__nav-menu header__nav-menu--scroll"
                            aria-labelledby="dropdownMenu3">
                            <li><a href="{% url 'core:about' %}">درباره ما</a></li>
                            <li><a href="{% url 'core:contact' %}">تماس با ما</a></li>
                            <li><a href="{% url 'core:privacy' %}">حریم خصوصی</a></li>
                        </ul>
                    </li>
                </ul>

                <div class="header__actions">
                    <form action="#" class="header__form">
                        <input class="header__form-input" type="text" placeholder="من دنبال ...">
                        <button class="header__form-btn" type="button">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path d="M21.71,20.29,18,16.61A9,9,0,1,0,16.61,18l3.68,3.68a1,1,0,0,0,1.42,0A1,1,0,0,0,21.71,20.29ZM11,18a7,7,0,1,1,7-7A7,7,0,0,1,11,18Z"/>
                            </svg>
                        </button>
                        <button type="button" class="header__form-close">
                            <svg width="20" height="20" viewBox="0 0 20 20" fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                      d="M14.3345 0.000183105H5.66549C2.26791 0.000183105 0.000488281 2.43278 0.000488281 5.91618V14.0842C0.000488281 17.5709 2.26186 20.0002 5.66549 20.0002H14.3335C17.7381 20.0002 20.0005 17.5709 20.0005 14.0842V5.91618C20.0005 2.42969 17.7383 0.000183105 14.3345 0.000183105ZM5.66549 1.50018H14.3345C16.885 1.50018 18.5005 3.23515 18.5005 5.91618V14.0842C18.5005 16.7653 16.8849 18.5002 14.3335 18.5002H5.66549C3.11525 18.5002 1.50049 16.7655 1.50049 14.0842V5.91618C1.50049 3.23856 3.12083 1.50018 5.66549 1.50018ZM7.07071 7.0624C7.33701 6.79616 7.75367 6.772 8.04726 6.98988L8.13137 7.06251L9.99909 8.93062L11.8652 7.06455C12.1581 6.77166 12.6329 6.77166 12.9258 7.06455C13.1921 7.33082 13.2163 7.74748 12.9984 8.04109L12.9258 8.12521L11.0596 9.99139L12.9274 11.8595C13.2202 12.1524 13.2202 12.6273 12.9273 12.9202C12.661 13.1864 12.2443 13.2106 11.9507 12.9927L11.8666 12.9201L9.99898 11.052L8.13382 12.9172C7.84093 13.2101 7.36605 13.2101 7.07316 12.9172C6.80689 12.6509 6.78269 12.2343 7.00054 11.9407L7.07316 11.8566L8.93843 9.99128L7.0706 8.12306C6.77774 7.83013 6.77779 7.35526 7.07071 7.0624Z"/>
                            </svg>
                        </button>
                    </form>

                    <button class="header__search" type="button">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                            <path d="M21.71,20.29,18,16.61A9,9,0,1,0,16.61,18l3.68,3.68a1,1,0,0,0,1.42,0A1,1,0,0,0,21.71,20.29ZM11,18a7,7,0,1,1,7-7A7,7,0,0,1,11,18Z"/>
                        </svg>
                    </button>
                    {% if request.user.is_anonymous %}
                    <a href="{% url 'accounts:login' %}" class="header__user">
                        <span>وارد شوید</span>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                            <path d="M20,12a1,1,0,0,0-1-1H11.41l2.3-2.29a1,1,0,1,0-1.42-1.42l-4,4a1,1,0,0,0-.21.33,1,1,0,0,0,0,.76,1,1,0,0,0,.21.33l4,4a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42L11.41,13H19A1,1,0,0,0,20,12ZM17,2H7A3,3,0,0,0,4,5V19a3,3,0,0,0,3,3H17a3,3,0,0,0,3-3V16a1,1,0,0,0-2,0v3a1,1,0,0,1-1,1H7a1,1,0,0,1-1-1V5A1,1,0,0,1,7,4H17a1,1,0,0,1,1,1V8a1,1,0,0,0,2,0V5A3,3,0,0,0,17,2Z"/>
                        </svg>
                    </a>
                    {% else %}
                    <a href="{% url 'accounts:profile' %}" class="header__user">
                        <span>پروفایل</span>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                            <path d="M20,12a1,1,0,0,0-1-1H11.41l2.3-2.29a1,1,0,1,0-1.42-1.42l-4,4a1,1,0,0,0-.21.33,1,1,0,0,0,0,.76,1,1,0,0,0,.21.33l4,4a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42L11.41,13H19A1,1,0,0,0,20,12ZM17,2H7A3,3,0,0,0,4,5V19a3,3,0,0,0,3,3H17a3,3,0,0,0,3-3V16a1,1,0,0,0-2,0v3a1,1,0,0,1-1,1H7a1,1,0,0,1-1-1V5A1,1,0,0,1,7,4H17a1,1,0,0,1,1,1V8a1,1,0,0,0,2,0V5A3,3,0,0,0,17,2Z"/>
                        </svg>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end header -->

templates/shared/partners.html
{% load static %}

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="partners owl-carousel">
                    <a class="partners__img">
                        <img src="{% static 'img/partners/3docean-light-background.png' %}" alt="">
                    </a>

                    <a href="" class="partners__img">
                        <img src="{% static 'img/partners/activeden-light-background.png' %}" alt="">
                    </a>

                    <a class="partners__img">
                        <img src="{% static 'img/partners/audiojungle-light-background.png' %}" alt="">
                    </a>

                    <a class="partners__img">
                        <img src="{% static 'img/partners/codecanyon-light-background.png' %}" alt="">
                    </a>

                    <a class="partners__img">
                        <img src="{% static 'img/partners/photodune-light-background.png' %}" alt="">
                    </a>

                    <a class="partners__img">
                        <img src="{% static 'img/partners/themeforest-light-background.png' %}" alt="">
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/shared/plan.html
{% load finance_filters %}

<form action="{% url 'finance:pay_plan' %}" method="post" id="modal-topup" class="zoom-anim-dialog modal modal--form mfp-hide">
    {% csrf_token %}
    <button class="modal__close" type="button">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
            <path d="M13.41,12l4.3-4.29a1,1,0,1,0-1.42-1.42L12,10.59,7.71,6.29A1,1,0,0,0,6.29,7.71L10.59,12l-4.3,4.29a1,1,0,0,0,0,1.42,1,1,0,0,0,1.42,0L12,13.41l4.29,4.3a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42Z"></path>
        </svg>
    </button>

    <h4 class="sign__title">خرید اشتراک جنگو مووی</h4>

    <div class="sign__group sign__group--row">
        <label class="sign__label">اعتبار فعلی :</label>
        <span class="sign__value">50,000 تومان</span>
    </div>

    <div class="sign__group sign__group--row">
        <label class="sign__label" for="value">انتخاب پلن :</label>
        <select class="sign__select" name="value" id="value">
            {% for plan in 'plans'|finance_actions %}
            <option name="plan" value="{{ plan.id }}"> {{ plan.name }} {{ plan.get_price }} تومان </option>
            {% endfor %}
        </select>

        <span class="sign__text sign__text--small">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.</span>
    </div>

    <div class="sign__group sign__group--row">
        <label class="sign__label">روش پرداخت :</label>

        <ul class="sign__radio">
            {% for gateway in 'gateways'|finance_actions %}
            <li>
                <input id="type{{ gateway.id }}" type="radio" name="gateway" value="{{ gateway.id }}" checked>
                <label for="type{{ gateway.id }}">{{ gateway.get_name_display }}</label>
            </li>
            {% endfor %}
        </ul>
    </div>

    <button class="sign__btn" type="submit">خرید اشتراک</button>
</form>

<section class="section section--pb0 section--gradient">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="section__title">پلن های اشتراک</h2>
                <p class="section__text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ.</p>
            </div>
        </div>

        <div dir="rtl" class="row">
            {% for plan in 'plans'|finance_actions %}

            {% if plan.best_plan %}
            <div class="col-12 col-xl-4 order-md-1 order-xl-2">
                <div class="plan plan--style2 plan--best">
                    <h3 class="plan__title">{{ plan.name }}</h3>
                    <span class="plan__price">{{ plan.get_price|floatformat:"-3g" }} ت <span>/ {{ plan.get_per_display }}</span></span>
                    <ul class="plan__list">
                        {% for attr in plan.attributes.all %}

                        {% if attr.is_active %}
                        <li class="green">
                            <svg width="19" height="14" viewBox="0 0 19 14" fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path d="M1.43994 6.95981L6.77477 12.2924L17.4399 1.62723" stroke-width="2"
                                      stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                            {{ attr.name }}
                        </li>
                        {% else %}
                        <li class="red">
                            <svg width="19" height="19" viewBox="0 0 19 19" fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path d="M17.596 1.59982L1.60938 17.5865" stroke-width="2" stroke-linecap="round"
                                      stroke-linejoin="round"/>
                                <path d="M17.601 17.5961L1.60101 1.5928" stroke-width="2" stroke-linecap="round"
                                      stroke-linejoin="round"/>
                            </svg>
                            {{ attr.name }}
                        </li>
                        {% endif %}

                        {% endfor %}
                    </ul>
                    {% if request.user.is_authenticated %}
                    <a class="plan__btn open-modal" href="#modal-topup">انتخاب پلن</a>
                    {% else %}
                    <a class="plan__btn" href="{% url 'accounts:login' %}">اول وارد حسابت خود شوید</a>
                    {% endif %}
                </div>
            </div>
            {% else %}
            <div class="col-12 col-md-6 col-xl-4 order-md-2 order-xl-1">
                <div class="plan plan--style2">
                    <h3 class="plan__title">{{ plan.name }}</h3>
                    <span class="plan__price">{{ plan.get_price|floatformat:"-3g" }} ت <span>/ {{ plan.get_per_display }}</span></span>
                    <ul class="plan__list">
                        {% for attr in plan.attributes.all %}

                        {% if attr.is_active %}
                        <li class="green">
                            <svg width="19" height="14" viewBox="0 0 19 14" fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path d="M1.43994 6.95981L6.77477 12.2924L17.4399 1.62723" stroke-width="2"
                                      stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                            {{ attr.name }}
                        </li>
                        {% else %}
                        <li class="red">
                            <svg width="19" height="19" viewBox="0 0 19 19" fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path d="M17.596 1.59982L1.60938 17.5865" stroke-width="2" stroke-linecap="round"
                                      stroke-linejoin="round"/>
                                <path d="M17.601 17.5961L1.60101 1.5928" stroke-width="2" stroke-linecap="round"
                                      stroke-linejoin="round"/>
                            </svg>
                            {{ attr.name }}
                        </li>
                        {% endif %}

                        {% endfor %}
                    </ul>

                    {% if request.user.is_authenticated %}
                    <a class="plan__btn open-modal" href="#modal-topup">انتخاب پلن</a>
                    {% else %}
                    <a class="plan__btn" href="{% url 'accounts:login' %}">اول وارد حسابت خود شوید</a>
                    {% endif %}
                </div>
            </div>
            {% endif %}

            {% endfor %}
        </div>
    </div>
</section>